function [Y] = f_compile(X, day, window)

% Y = mean(X(1).Mud(:,:,day:(day+window)),3)...
%     +mean(X(1).CarbSand(:,:,day:(day+window)),3)...
%     +mean(X(1).FineSed(:,:,day:(day+window)),3);

% Y = mean(X(1).Mud_mineral(:,:,day:(day+window)),3)...
%     +mean(X(1).Mud_carbonate(:,:,day:(day+window)),3)...
%     +mean(X(1).Sand_mineral(:,:,day:(day+window)),3)...
%     +mean(X(1).Sand_carbonate(:,:,day:(day+window)),3)...
%     +mean(X(1).FineSed(:,:,day:(day+window)),3)...
%     +mean(X(1).Dust(:,:,day:(day+window)),3);

Y = mean(X(1).Mud_mineral(:,:,day:(day+window)),3)...
    +mean(X(1).Mud_carbonate(:,:,day:(day+window)),3)...
    +mean(X(1).FineSed(:,:,day:(day+window)),3)...
    +mean(X(1).Dust(:,:,day:(day+window)),3);
